# Generated by Django 5.1.15 on 2026-09-10 04:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0018_bulkresumejob_bulkresumeitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidateprofile",
            name="resume",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="resumes/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "doc", "docx"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="duplicateresumelog",
            name="action_taken",
            field=models.CharField(
                choices=[
                    ("SKIPPED", "Skipped"),
                    ("UPDATED", "Updated"),
                    ("MERGED", "Merged"),
                ],
                max_length=50,
            ),
        ),
    ]
