# Generated by Django 5.1.15 on 2026-09-24 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="website",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
