# Generated by Django 5.1.15 on 2026-09-17 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0011_job_ai_matching_enabled_job_department_job_education_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="source",
            field=models.CharField(
                choices=[
                    ("ADMIN", "HireNest Admin"),
                    ("EMPLOYER", "External Employer"),
                ],
                db_index=True,
                default="EMPLOYER",
                help_text="Who owns this posting: the HireNest admin or an external employer.",
                max_length=20,
            ),
        ),
    ]
